'use client';
import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Loader2, Search } from 'lucide-react';
import { paymentTransactionsApi } from '@/lib/payments/transactions';

export default function PaymentTransactionHistoryModal({ open, onOpenChange }: { open:boolean; onOpenChange:(v:boolean)=>void }) {
  const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [q,setQ]=useState('');
  useEffect(()=>{ if(!open)return; const t=setTimeout(()=>{setLoading(true);void paymentTransactionsApi.list(q).then(r=>setRows(r?.error?[]:(r?.data||[]))).finally(()=>setLoading(false));},250);return()=>clearTimeout(t);},[open,q]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex max-h-[88vh] max-w-5xl flex-col overflow-hidden"><DialogHeader><DialogTitle>Payment Transaction History</DialogTitle><DialogDescription>Audit trail for Final Cost status changes, completed payments, and POS sales.</DialogDescription></DialogHeader><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} className="pl-9" placeholder="Search tracking number, customer, event, reference..."/></div><div className="min-h-0 flex-1 overflow-auto rounded-lg border"><table className="w-full min-w-[820px] text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-3 text-left">Date</th><th className="p-3 text-left">Transaction</th><th className="p-3 text-left">Customer / Tracking</th><th className="p-3 text-left">Status</th><th className="p-3 text-right">Amount</th><th className="p-3 text-left">Staff / Reference</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-12 text-center"><Loader2 className="mx-auto h-5 w-5 animate-spin"/></td></tr>:rows.length===0?<tr><td colSpan={6} className="p-12 text-center text-muted-foreground">No payment history found.</td></tr>:rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 whitespace-nowrap">{new Date(r.createdAt).toLocaleString('en-PH')}</td><td className="p-3"><Badge variant="outline">{String(r.entityType).replace(/_/g,' ')}</Badge><p className="mt-1 font-medium">{String(r.eventType).replace(/_/g,' ')}</p></td><td className="p-3"><p className="font-medium">{r.customerName||'—'}</p><p className="text-xs text-muted-foreground">{r.trackingNumber||'No appointment'}</p></td><td className="p-3">{r.fromStatus||r.toStatus?<>{r.fromStatus||'—'} → <b>{r.toStatus||'—'}</b></>:'—'}</td><td className="p-3 text-right font-mono">{r.amount!=null?`₱${Number(r.amount).toLocaleString('en-PH',{minimumFractionDigits:2})}`:'—'}</td><td className="p-3"><p>{r.staffName||r.staffUsername||'System / customer'}</p><p className="text-xs text-muted-foreground">{r.referenceNumber||r.paymentMethod||'—'}</p></td></tr>)}</tbody></table></div></DialogContent></Dialog>;
}
